### PR TITLE
Recusive Check, hyperlink support and code readability

### PR DESCRIPTION
**Pull request by fritz-hh**
Hi Gaurav,

This pull request replaces #10, #11, #12, #13 that can be discarded.

This is a quite big pull request, I hope you won't be frightened when you see it ;-)
I have tested it quite extensively (and also added also some test files in this pull request).
Now it contains more or less everything I currently need!

Julien

New functions:

* Support for hyperlinks
* Support for "link:" macro
* Support for checking references from treeView (also recursively)
* Improved notification to mention the name of the file that contained the bad reference (important in case of recursive checks where many adoc files are checked)

Other improvements:

* code quality
  * reducing nesting to a minimum to improve readability and maintainability (without changing the overall structure)
    * using Invert “if” statement where possible (see: https://stackoverflow.com/questions/268132/invert-if-statement-to-reduce-nesting)
    * using if, elif, else, rather than nested ifs when possible
    * move some function definition higher
  * consistant impementation of all pattern matching sections
  * make use of the promise resolve method to pass results rather than using a global variable "allGood"
* Various robustness improvements
* add test asciidoc files
* update README

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
Thanks @fritz-hh for your extensive work on this. This is on my list, I will go through this soon.

**Comment by fritz-hh** [comment]
:+1:

**Comment by fritz-hh** [comment]
I realized today, that there are cases, where URLs are not correctly matched (e.g. when they are followed by a "."). I think a good solution would be to use the same regex as in the atom asciidoc syntax highlighting package. I plan to correct that tomorrow.

**Comment by gaurav-nelson** [comment]
@fritz-hh I did a similar project and plan was to include everything here, or add reference check capabilities there, have a look at https://github.com/gaurav-nelson/asciidoc-link-check (it uses https://github.com/gaurav-nelson/asciidoc-link-extractor/)

**Comment by gaurav-nelson** [comment]
@fritz-hh also can you please combine all these commits into 1 commit (idle) or upto 4 commits, it helps in keeping clean history, plus makes it easy to check and track, thanks.

**Comment by fritz-hh** [comment]
@gaurav-nelson thanks for your answer. I will create a new pull request with up to 4 commits. I could also create 2 pull requests 1 for the recursive check and refactoring, and one for the link check. Would you prefer that?

Thanks for pointing to the 2 repositories. I will have a closer look at them.

**Comment by fritz-hh** [comment]
I had a look at  https://github.com/gaurav-nelson/asciidoc-link-check and https://github.com/gaurav-nelson/asciidoc-link-extractor/

In asciidoc-link-check, you use [link-check](https://github.com/tcort/link-check). I must say that this npm package is much better than the one I used (it handles also email addresses and it is possible to tune the acceptable HTTP status code). Therefore, I think, we should go for this one.

Concerning the URL matching, I saw your proposal. Here I would prefer to go for the pattern matching used by atom-language-asciidoc (the asciidoc syntax highlighting package for atom developed by asciidoctor) (see: https://github.com/asciidoctor/atom-language-asciidoc/blob/master/grammars/repositories/inlines/link-macro-grammar.cson. I did not find the pattern used by [asciidoctor](https://github.com/asciidoctor/asciidoctor) itself, but I would assume that it is the same than the one used by the syntax highlighter). Each time the asciidoctor tool chain generate a link, I would want asciidoc-reference-check to tell me if this link is bad. Now if we use a more restrictive pattern match (more restrictive then asciidoctor), their is a risk that a bad URL will be silently ignored. As the [link extractor](https://github.com/gaurav-nelson/asciidoc-link-extractor/) seems to be more restrictive, I would prefer to go for the regex used by the syntax highlighter.

What is your point of view on that?
If you agree with me, I could send you 2 new pull request (as mentioned in my earlier post)

**Comment by gaurav-nelson** [comment]
Thanks @fritz-hh
I agree, we should use the atom-language-asciidoc highlighter. About the PRs, it would make sense to have each feature as a seperate PR. Thanks

**Comment by fritz-hh** [comment]
OK. I will send you the pull reqeuest in the next days, (I am quite busy currently)

**Comment by fritz-hh** [comment]
replaced by #15

**Pull request closed without merging**
