### PR TITLE
Add support for recursive check

### PR DESCRIPTION
**Pull request by fritz-hh**
Add a dropdown menu item in treeView to trigger recursive check of all adoc files in a folder and in its subfolders recursively

### CODE REVIEW

**Comment by fritz-hh** [comment]
Here is the recursive check :-)
I understood, that you would like to check if the pull-request is fine, so I won't merge it, before you confirm that it is OK for you.

**Comment by gaurav-nelson** [comment]
Thanks @fritz-hh Will check this one today

**Comment by gaurav-nelson** [comment]
Sorry for a delayed response and thanks @fritz-hh for this PR,

It works as you described it would. I am merging this now. 

I do have following suggestion:

- Maybe we could suppress the success messages with 'no internal references found` because for a folder with too many files it shows long list of messages and I feel it servers no purpose for folder level function.

**Comment by fritz-hh** [comment]
> Maybe we could suppress the success messages with 'no internal references found` because for a folder with too many files it shows long list of messages and I feel it servers no purpose for folder level function.

Yes. I fully agree. Feel free to change that point.

**Pull request merged**
