### PR TITLE
support bibliography anchors

### PR DESCRIPTION
**Pull request by fritz-hh**
add support for bibliography anchors with tripple square brackets
(see: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#bibliography)

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
Thanks you for the PR @fritz-hh I will test them shortly.

**Comment by gaurav-nelson** [comment]
Should we consider this as well? 
```
_The Pragmatic Programmer_ <<pp>> should be required reading for all developers.


== Reference
[[[pp]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
```

OR the format will alway be ` - [[[anchor]]] `

**Comment by fritz-hh** [comment]
From my understanding, the bibliography should be a bulleted list. (see: http://asciidoc.org/userguide.html#_bibliography_lists).
I guess that both "-" and "\*" should be allowed. Even though the example I found all start with "-" (at least asciidoctor supports both "\*" and "-"

**Comment by gaurav-nelson** [comment]
[PR review - support bibliography anchors](https://trello.com/c/Q8SnCVcW/8-pr-review-support-bibliography-anchors)

**Comment by gaurav-nelson** [comment]
Thanks @fritz-hh merging this now.

**Comment by fritz-hh** [comment]
Thanks a lot!

**Pull request merged**
